import React, { useRef, useEffect, useState } from 'react';
import progressService from '../../services/progress.service.js';
import toast from 'react-hot-toast';
import { FileText, Layers, BrainCircuit, Clock, ArrowUpRight, Sparkles } from 'lucide-react';

const DashboardPage = () => {
  const [dashboardData, setDashboardData] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const hasFetched = useRef(false);

  useEffect(() => {
    if (hasFetched.current) return;
    hasFetched.current = true;

    const fetchDashboard = async () => {
      try {
        const fetchedData = await progressService.getDashboard();
        setDashboardData(fetchedData?.data || {});
      } catch {
        toast.error('Failed to fetch dashboard data');
      } finally {
        setIsLoading(false);
      }
    };

    fetchDashboard();
  }, []);

  const overview = dashboardData?.overview || {};
  const recentActivity = dashboardData?.recentActivity || {};

  const stats = [
    {
      label: 'Documents',
      value: overview?.documentCount || 0,
      icon: FileText,
      hint: 'uploaded & indexed',
    },
    {
      label: 'Flashcards',
      value: overview?.flashcardsetCount || 0,
      icon: Layers,
      hint: 'across all sets',
    },
    {
      label: 'Quizzes',
      value: overview?.quizzesCount || 0,
      icon: BrainCircuit,
      hint: 'generated by AI',
    },
  ];

  const activities = [
    ...(recentActivity?.documents || []).map((doc) => ({
      id: doc._id,
      description: doc.title,
      timestamp: doc.lastAccessed || doc.createdAt,
      link: `/documents/${doc._id}`,
      type: 'Document',
    })),
    ...(recentActivity?.quizzes || []).map((quiz) => ({
      id: quiz._id,
      description: quiz.title,
      timestamp: quiz.completedAt || quiz.createdAt,
      link: `/quizzes/${quiz._id}`,
      type: 'Quiz',
    })),
  ].sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));

  if (isLoading) {
    return (
      <div className="min-h-[50vh] flex flex-col items-center justify-center gap-4">
        <div className="relative w-12 h-12">
          <div className="absolute inset-0 rounded-full border-2 border-white/10" />
          <div className="absolute inset-0 rounded-full border-2 border-transparent border-t-accent border-r-primary animate-spin" />
        </div>
        <p className="text-xs font-semibold tracking-[0.2em] uppercase text-subtle">
          Loading workspace
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      {/* Hero */}
      <section className="surface relative overflow-hidden p-7 sm:p-9">
        <div className="pointer-events-none absolute -top-28 -right-20 h-64 w-64 rounded-full bg-primary/25 blur-3xl" />
        <div className="pointer-events-none absolute -bottom-32 left-10 h-56 w-56 rounded-full bg-accent/20 blur-3xl" />

        <div className="relative z-10 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <p className="eyebrow mb-3">Overview</p>
            <h1 className="text-3xl sm:text-4xl font-bold tracking-tight leading-tight">
              Your learning, <span className="text-gradient">beautifully organized</span>
            </h1>
            <p className="page-subtitle max-w-lg">
              Track every document, flashcard set and quiz you have created with AI.
            </p>
          </div>
          <span className="chip chip-live self-start sm:self-auto">
            <span className="w-1.5 h-1.5 rounded-full bg-success animate-pulse" />
            Synced
          </span>
        </div>
      </section>

      {/* Stats */}
      <section className="grid grid-cols-1 sm:grid-cols-3 gap-5">
        {stats.map((stat, index) => (
          <div key={index} className="surface surface-hover p-6 group">
            <div className="flex justify-between items-start mb-5">
              <div>
                <p className="text-[0.68rem] font-bold tracking-[0.18em] uppercase text-subtle">
                  {stat.label}
                </p>
                <p className="mt-1 text-xs text-muted">{stat.hint}</p>
              </div>
              <div className="icon-tile">
                <stat.icon size={18} />
              </div>
            </div>
            <p className="text-4xl font-bold tracking-tight text-foreground">
              {stat.value}
            </p>
            <div className="mt-4 h-1 w-full rounded-full bg-white/5 overflow-hidden">
              <div className="h-full w-1/3 bg-gradient-to-r from-primary to-accent rounded-full transition-all duration-700 group-hover:w-2/3" />
            </div>
          </div>
        ))}
      </section>

      {/* Activity */}
      <section>
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2.5">
            <Clock className="text-accent" size={18} />
            <h2 className="text-lg font-bold tracking-tight">Recent activity</h2>
          </div>
          <span className="chip">
            {activities.length} {activities.length === 1 ? 'entry' : 'entries'}
          </span>
        </div>

        {activities.length > 0 ? (
          <div className="surface divide-y divide-white/6 overflow-hidden">
            {activities.map((activity) => (
              <a
                key={activity.id}
                href={activity.link}
                className="flex items-center justify-between gap-4 px-5 py-4
                hover:bg-fill-strong transition group"
              >
                <div className="flex items-center gap-4 min-w-0">
                  <span className="icon-tile !w-10 !h-10 !rounded-lg shrink-0">
                    <Sparkles size={15} />
                  </span>
                  <div className="min-w-0">
                    <p className="text-sm font-semibold text-foreground truncate">
                      {activity.description}
                    </p>
                    <p className="text-xs text-subtle">
                      {activity.type} ·{' '}
                      {new Date(activity.timestamp).toLocaleDateString(undefined, {
                        month: 'short',
                        day: 'numeric',
                        year: 'numeric',
                      })}
                    </p>
                  </div>
                </div>

                <span className="inline-flex items-center gap-1 text-xs font-semibold text-muted
                  group-hover:text-accent transition shrink-0">
                  Open
                  <ArrowUpRight size={14} />
                </span>
              </a>
            ))}
          </div>
        ) : (
          <div className="surface p-10 text-center">
            <div className="icon-tile mx-auto mb-4 !w-14 !h-14">
              <Clock size={22} />
            </div>
            <p className="font-semibold mb-1">No recent activity yet</p>
            <p className="text-sm text-muted">
              Upload a document and your history will appear here.
            </p>
          </div>
        )}
      </section>
    </div>
  );
};

export default DashboardPage;
